package com.bio.sequencing.models;

import java.time.Instant;
import java.util.HashMap;
import java.util.Map;

public class AnalysisResult {

    public enum Status {
        CREATED,
        RUNNING,
        COMPLETED,
        FAILED
    }

    private String jobId;

    private Status status;

    /**
     * Human-readable message.
     */
    private String message;

    /**
     * Results returned by Bioconductor.
     */
    private Map<String, Object> results;

    /**
     * Files generated by the analysis.
     *
     * Example:
     * aligned -> /results/aligned.fasta
     * report  -> /results/report.html
     */
    private Map<String, String> outputFiles;

    /**
     * Error information if the analysis failed.
     */
    private String error;

    private Instant startedAt;

    private Instant completedAt;

    public AnalysisResult() {
        this.results = new HashMap<>();
        this.outputFiles = new HashMap<>();
    }

    public AnalysisResult(
            String jobId,
            Status status,
            String message) {

        this.jobId = jobId;
        this.status = status;
        this.message = message;
        this.results = new HashMap<>();
        this.outputFiles = new HashMap<>();
    }

    public static AnalysisResult running(String jobId) {

        AnalysisResult result = new AnalysisResult(
                jobId,
                Status.RUNNING,
                "Bioconductor analysis started"
        );

        result.setStartedAt(Instant.now());

        return result;
    }

    public static AnalysisResult completed(String jobId) {

        AnalysisResult result = new AnalysisResult(
                jobId,
                Status.COMPLETED,
                "Bioconductor analysis completed"
        );

        result.setCompletedAt(Instant.now());

        return result;
    }

    public static AnalysisResult failed(
            String jobId,
            String error) {

        AnalysisResult result = new AnalysisResult(
                jobId,
                Status.FAILED,
                "Bioconductor analysis failed"
        );

        result.setError(error);
        result.setCompletedAt(Instant.now());

        return result;
    }

    public String getJobId() {
        return jobId;
    }

    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Map<String, Object> getResults() {
        return results;
    }

    public void setResults(Map<String, Object> results) {
        this.results = results;
    }

    public Map<String, String> getOutputFiles() {
        return outputFiles;
    }

    public void setOutputFiles(Map<String, String> outputFiles) {
        this.outputFiles = outputFiles;
    }

    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public Instant getStartedAt() {
        return startedAt;
    }

    public void setStartedAt(Instant startedAt) {
        this.startedAt = startedAt;
    }

    public Instant getCompletedAt() {
        return completedAt;
    }

    public void setCompletedAt(Instant completedAt) {
        this.completedAt = completedAt;
    }
}